### ISSUE TITLE
error in "engine/defaults.py"

### ISSUE THREAD

**Issue by chenrxi** [ubc-vision/UniT#1]
hi, thanks for your job. In "engine/defaults.py", object 'Trainer' has no attribute '_data_loader_iter', how can I correct the code?

**Comment by siddheshk** [comment]
Hi, this might be due to the version of `detectron2` you have installed. I would recommend using `0.2.1` or earlier. You can see the `_data_loader_iter` present in these versions here: https://github.com/facebookresearch/detectron2/blob/v0.2.1/detectron2/engine/train_loop.py#L208

**Comment by chenrxi** [comment]
Thanks. Another question: What kind of GPU do you use and How can I reproduce the result in your paper reported?
